a1/urls.py
from django.conf.urls import url
from .views import *
from .custom_auth import auth_login, auth_logout

urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^login/', login, name='login'),

    url(r'^custom_auth/login/$', auth_login, name='auth_login'),
    url(r'^custom_auth/logout/$', auth_logout, name='auth_logout'),

]

a2/urls.py
from django.conf.urls import url
from .views import *


urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^edit-profile/', edit_profile, name='edit_profile'),
    url(r'^update-profile/', update_profile, name='update_profile'),
    url(r'^delete-status/(?P<id>\d+)/$', delete_status, name='delete'),
    url(r'^add-status/', add_status, name='add'),
]

project_mother/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic import RedirectView
import a1.urls as a1
import a2.urls as a2
import a3.urls as a3
import a4.urls as a4


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^a1/', include(a1, namespace='a1')),
    url(r'^a3/', include(a3, namespace='a3')),
    url(r'^a2/', include(a2, namespace='a2')),
    url(r'^a4/', include(a4, namespace='a4')),
    url(r'^$', RedirectView.as_view(url='/a1/', permanent = 'true'), name = 'a1')
    ]

a2/models.py
from django.db import models
from a4.models import Teman, Keahlian

# Create your models here.
class Profile(models.Model):
    name = models.CharField(max_length = 100, null = True)
    npm = models.CharField(max_length = 20, null = True)
    mastery = models.CharField(max_length = 200, null = True)
    email = models.EmailField(max_length = 100, null = True)
    profileLinkedIn = models.URLField(max_length = 200, blank=True,null = True, default = "Kosong")

class Status(models.Model):
    pengguna = models.ForeignKey(Teman)
    status = models.CharField(max_length=1000)
    created_date = models.DateTimeField(auto_now_add=True)

    def as_dict(self): # pragma: no cover
        return {
            "status": self.status,
            "created_date": self.created_date,
        }

class Comment(models.Model):
	pengguna = models.ForeignKey(Status,on_delete=models.CASCADE)
	comment = models.CharField(max_length=1000)
	created_date = models.DateTimeField(auto_now_add=True)

a2/forms.py
from django import forms

class Status_Form(forms.Form):
    error_messages = {
        'required': 'Tolong isi input ini',
    }
    description_attrs = {
        'type': 'text',
        'cols': 50,
        'rows': 4,
        'class': 'status-form-textarea',
        'placeholder':'  write here...',
        'id': 'field'
    }
    status = forms.CharField(label='', required=True, widget=forms.Textarea(attrs=description_attrs))

a2/views.py
from django.shortcuts import render
from django.urls import reverse
from a4.models import Teman
from a2.models import *
from django.forms.models import model_to_dict
from django.http import *
from .utils import *
import requests
from .forms import Status_Form


# Create your views here.
response = {}
def index(request): # pragma: no cover
    response['author'] = "Muhammad Ikhsan Kurniawan"
    response['riwayats'] = get_riwayat()
    html = "a2/a2.html"
    friends = Teman.objects.all()
    friend_list = []

    for friend in friends:
        friend_list.append(model_to_dict(friend))

    # daftar = {'friend_list' : friend_list}
    response['friend_list'] = friend_list
    kode_identitas = get_data_user(request, 'kode_identitas')
    user_exist = check_user_in_database(request, kode_identitas)
    if (user_exist):
    	user = Teman.objects.get(npm = kode_identitas)
    else:
    	user = create_new_user(request)
    pengguna = Teman.objects.get(npm = kode_identitas)
    response['status'] = pengguna.status_set.all()
    # print(response['status'])
    stat = Status.objects.all().order_by('-id')
    if (len(stat) > 0):
        message = stat[0]
        newMessage = message.status
        time = message.created_date
    else:
        newMessage = "You have not posted yet"
        # time = date(datetime.now().year,datetime.now().month,datetime.now().day)
    response['latestMessage'] = newMessage
    response['jumlah_status'] = pengguna.status_set.count()
    response['daftar_riwayat'] = get_riwayat()
    response['user'] = user
    status = Status.objects.filter(pengguna=pengguna).order_by('-id')
    response['status'] = status
    response['status_form'] = Status_Form
    return render(request, html, response)

def friends_list(request): # pragma: no cover
    friends = Teman.objects.all()
    friend_list = []

    for friend in friends:
        friend_list.append(model_to_dict(friend))

    daftar = {'friend_list' : friend_list}
    return JsonResponse(daftar)

API_RIWAYAT = 'https://private-e52a5-ppw2017.apiary-mock.com/riwayat'

def get_riwayat(): # pragma: no cover
	riwayats = requests.get(API_RIWAYAT)
	return riwayats.json()

def edit_profile(request): # pragma: no cover
    kode_identitas = get_data_user(request, 'kode_identitas')
    pengguna = Teman.objects.get(npm = kode_identitas)
    response['user'] = pengguna
    html = 'a2/edit.html'
    return render(request, html, response)

def update_profile(request): # pragma: no cover
    if request.method == 'POST':
        kode_identitas = get_data_user(request, 'kode_identitas')
        pengguna = Teman.objects.get(npm = kode_identitas)
        fullname = request.POST['full_name']
        url_linkedin = request.POST['url_linkedin']
        print(url_linkedin)
        picture_url = request.POST['picture_url']
        email = request.POST['email']
        headline = request.POST['headline']
        pengguna.nama = fullname
        pengguna.url_linkedin = url_linkedin
        pengguna.foto = picture_url
        pengguna.email = email
        pengguna.headline = headline
        pengguna.save()
        response['Status_form'] = Status_Form
        kode_identitas = get_data_user(request,'kode_identitas')
        pengguna = Teman.objects.get(npm = kode_identitas)
        response['status'] = pengguna.status_set.all()
		# print(response['status'])
        stat = Status.objects.all().order_by('-id')
        if (len(stat) > 0):
            message = stat[0]
            newMessage = message.status
            time = message.created_date
        else:
            newMessage = "You have not posted yet"
            time = date(datetime.now().year,datetime.now().month,datetime.now().day)
        response['latestMessage'] = newMessage
        response['jumlah_status'] = pengguna.status_set.count()
        response['daftar_riwayat'] = views.get_daftar_riwayat()
        return HttpResponseRedirect(reverse('a2:edit_profile'))

def add_status(request): # pragma: no cover
	kode_identitas = get_data_user(request,'kode_identitas')
	pengguna = Teman.objects.get(npm = kode_identitas)
	form = Status_Form(request.POST or None)
	if(request.method == 'POST' and form.is_valid()):
		response['status'] = request.POST['status']
		status = Status(status=response['status'], pengguna=pengguna)
		status.save()
	return HttpResponseRedirect(reverse('a2:index'))

def delete_status(request, id): # pragma: no cover
	kode_identitas = get_data_user(request,'kode_identitas')
	pengguna = Teman.objects.get(npm = kode_identitas)
	status = pengguna.status_set.filter(pk=id)
	status.delete()
	return HttpResponseRedirect(reverse('a2:index'))

a2/templates/a2/a2.html
{% extends "a2/layout/base.html" %}
{% block content %}

<h1> Selamat Datang! </h1>
<a href="{% url 'a2:edit_profile' %}"> Edit Profile </a>

<ul class="nav nav-tabs nav-justified" role="tablist">
        <li role="presentation" class="active">
            <a href="#profile" aria-controls="home" role="tab" data-toggle="tab"> Profile </a>
        </li>
        <li role="presentation">
            <a href="#riwayat" aria-controls="settings" role="tab" data-toggle="tab"> Riwayat </a>
        </li>
        <li role="presentation">
            <a href="#status" aria-controls="settings" role="tab" data-toggle="tab"> Status </a>
        </li>
        <li role="presentation">
            <a href="#teman" aria-controls="settings" role="tab" data-toggle="tab"> Teman </a>
        </li>
    </ul>

    <!-- Tab panes -->
    <div class="tab-content">
        <div role="tabpanel" class="tab-pane fade in active" id="profile">
            {% include 'a2/tables/profile.html' %}
        </div>
        <div role="tabpanel" class="tab-pane fade" id="riwayat">
            {% include 'a3/riwayat-page.html' %}
        </div>
        <div role="tabpanel" class="tab-pane fade" id="status">
            {% include 'a2/tables/status.html' %}
        </div>
        <div role="tabpanel" class="tab-pane fade" id="teman">
            {% include 'a4/a4.html' %}
        </div>
    </div>
</div>
<script type="in/Login"></script>

<script type="text/javascript" src="//platform.linkedin.com/in.js">
    api_key:   81qqfocgbrw8fy
    authorize: true
    onLoad: onLinkedInLoad
</script>

<script type="text/javascript">

    // Setup an event listener to make an API call once auth is complete
    function onLinkedInLoad() {
        IN.Event.on(IN, "auth", getProfileData);
    }

    // Handle the successful return from the API call
    function onSuccess(data) {
        console.log(data);
    }

    // Handle an error response from the API call
    function onError(error) {
        console.log(error);
    }

    // Use the API call wrapper to request the member's basic profile data
    function getProfileData() {
        IN.API.Raw("/people/~").result(onSuccess).error(onError);
    }

</script>
{% endblock %}

a2/templates/a2/edit.html
{% extends "a2/layout/base.html" %}
{% load staticfiles %}
{% block content %}
<div class="profile">
  <div class="profilePic">
    <img class="photo" src="{{ user.foto }}">
  </div>
  <script type="in/Login"></script>
  <div class="containerContent">
    <div class="content">
      <p><b>Nama: </b><span id="fullName">{{ user.nama }}</span></p>
      <p><b>NPM: </b>{{ user.npm }}</p>
      <p><b>Keahlian: </b>{% for ii in split_expertise %} <span class="expert">{{ ii }}</span> {% endfor %}</p>
      <p><b>Email: </b>{{ user.email }}</p>
      <p><b>Profile LinkedIn: </b><span id="profileUrl"><a href="{{ user.url_linkedin }}">{{ user.url_linkedin }}</a></span></p>

      <div class="skillChooserContainer">
        <div>
          <h2>Keahlian</h2>
          <select>
            <option>Java</option>
            <option>Python</option>
            <option>Web Development</option>
            <option>Leadership</option>
          </select>
        </div>
        <div>
          <h2>Level</h2>
          <select>
            <option>Beginner</option>
            <option>Intermediate</option>
            <option>Expert</option>
          </select>
        </div>
      </div>
      <div class="editProfileButtonContainer">
        <a class="editProfileButton">Save</a>
          <a onclick="logOutFromLinkedin();" class="editProfileButton">Logout</a>
      </div>
    </div>
  </div>
</div>
<script
  src="https://code.jquery.com/jquery-3.2.1.min.js"
  integrity="sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4="
  crossorigin="anonymous">
</script>
<script type="text/javascript" src="//platform.linkedin.com/in.js">
    api_key: 81qqfocgbrw8fy
    onLoad: onLinkedInLoad
    authorize: true
    lang:
</script>
<script type="text/javascript">
    // Setup an event listener to make an API call once auth is complete
    function onLinkedInLoad() {
        IN.Event.on(IN, "auth", getProfileData);
    }

    // Handle the successful return from the API call
    function onSuccess(data) {
        console.log(data);
        const fullName = data.firstName+" "+data.lastName;
        const profileUrl = data.publicProfileUrl;
        updateProfile(data);
    }

    function updateProfile(data) {
      $.ajax({
        method : 'POST',
        url : "{% url 'a2:update_profile' %}",
        data : {
          'full_name' : data.firstName+" "+data.lastName,
          'url_linkedin': data.publicProfileUrl,
          'picture_url': data.pictureUrl,
          'email': data.emailAddress,
          'headline': data.headline,
        },
        dataType : 'json',
        success : function(response) {
          window.location = '/a2';
        },
        error : function(error) {
          console.log(error);
        }
      });
    }

    // Handle an error response from the API call
    function onError(error) {
        console.log(error);
    }

    // Use the API call wrapper to request the member's basic profile data
    function getProfileData() {
        IN.API.Raw("/people/~:(first-name,last-name,headline,email-address,picture-url,public-profile-url)").result(onSuccess).error(onError);
    }

    function logOutFromLinkedin() {
      IN.User.logout(logOut);
    }

    function logOut() {
      $.ajax({
        method : 'POST',
        url : "{% url 'a1:auth_logout' %}",
        success : function(response) {
          window.location.reload();
        },
        error : function(error) {
          console.log(error);
        }
      });
    }
</script>
{% endblock %}