a1/urls.py
from django.conf.urls import url
from .views import *
from .custom_auth import auth_login, auth_logout

urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^login/', login, name='login'),

    url(r'^custom_auth/login/$', auth_login, name='auth_login'),
    url(r'^custom_auth/logout/$', auth_logout, name='auth_logout'),

]

a2/urls.py
from django.conf.urls import url
from .views import *


urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^edit-profile/', edit_profile, name='edit_profile'),
    url(r'^update-profile/', update_profile, name='update_profile'),
    url(r'^delete-status/(?P<id>\d+)/$', delete_status, name='delete'),
    url(r'^add-status/', add_status, name='add'),
]

project_mother/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic import RedirectView
import a1.urls as a1
import a2.urls as a2
import a3.urls as a3
import a4.urls as a4


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^a1/', include(a1, namespace='a1')),
    url(r'^a3/', include(a3, namespace='a3')),
    url(r'^a2/', include(a2, namespace='a2')),
    url(r'^a4/', include(a4, namespace='a4')),
    url(r'^$', RedirectView.as_view(url='/a1/', permanent = 'true'), name = 'a1')
    ]

a2/models.py
from django.db import models
from a4.models import Teman, Keahlian

# Create your models here.
class Profile(models.Model):
    name = models.CharField(max_length = 100, null = True)
    npm = models.CharField(max_length = 20, null = True)
    mastery = models.CharField(max_length = 200, null = True)
    email = models.EmailField(max_length = 100, null = True)
    profileLinkedIn = models.URLField(max_length = 200, blank=True,null = True, default = "Kosong")

class Status(models.Model):
    pengguna = models.ForeignKey(Teman)
    status = models.CharField(max_length=1000)
    created_date = models.DateTimeField(auto_now_add=True)

    def as_dict(self): # pragma: no cover
        return {
            "status": self.status,
            "created_date": self.created_date,
        }

class Comment(models.Model):
	pengguna = models.ForeignKey(Status,on_delete=models.CASCADE)
	comment = models.CharField(max_length=1000)
	created_date = models.DateTimeField(auto_now_add=True)

a2/forms.py
from django import forms

class Status_Form(forms.Form):
    error_messages = {
        'required': 'Tolong isi input ini',
    }
    description_attrs = {
        'type': 'text',
        'cols': 50,
        'rows': 4,
        'class': 'status-form-textarea',
        'placeholder':'  write here...',
        'id': 'field'
    }
    status = forms.CharField(label='', required=True, widget=forms.Textarea(attrs=description_attrs))

a2/views.py
from django.shortcuts import render
from django.urls import reverse
from a4.models import Teman
from a2.models import *
from django.forms.models import model_to_dict
from django.http import *
from .utils import *
import requests
from .forms import Status_Form


# Create your views here.
response = {}
def index(request): # pragma: no cover
    response['author'] = "Muhammad Ikhsan Kurniawan"
    response['riwayats'] = get_riwayat()
    html = "a2/a2.html"
    friends = Teman.objects.all()
    friend_list = []

    for friend in friends:
        friend_list.append(model_to_dict(friend))

    # daftar = {'friend_list' : friend_list}
    response['friend_list'] = friend_list
    kode_identitas = get_data_user(request, 'kode_identitas')
    user_exist = check_user_in_database(request, kode_identitas)
    if (user_exist):
    	user = Teman.objects.get(npm = kode_identitas)
    else:
    	user = create_new_user(request)
    pengguna = Teman.objects.get(npm = kode_identitas)
    response['status'] = pengguna.status_set.all()
    # print(response['status'])
    stat = Status.objects.all().order_by('-id')
    if (len(stat) > 0):
        message = stat[0]
        newMessage = message.status
        time = message.created_date
    else:
        newMessage = "You have not posted yet"
        # time = date(datetime.now().year,datetime.now().month,datetime.now().day)
    response['latestMessage'] = newMessage
    response['jumlah_status'] = pengguna.status_set.count()
    response['daftar_riwayat'] = get_riwayat()
    response['user'] = user
    status = Status.objects.filter(pengguna=pengguna).order_by('-id')
    response['status'] = status
    response['status_form'] = Status_Form
    return render(request, html, response)

def friends_list(request): # pragma: no cover
    friends = Teman.objects.all()
    friend_list = []

    for friend in friends:
        friend_list.append(model_to_dict(friend))

    daftar = {'friend_list' : friend_list}
    return JsonResponse(daftar)

API_RIWAYAT = 'https://private-e52a5-ppw2017.apiary-mock.com/riwayat'

def get_riwayat(): # pragma: no cover
	riwayats = requests.get(API_RIWAYAT)
	return riwayats.json()

def edit_profile(request): # pragma: no cover
    kode_identitas = get_data_user(request, 'kode_identitas')
    pengguna = Teman.objects.get(npm = kode_identitas)
    response['user'] = pengguna
    html = 'a2/edit.html'
    return render(request, html, response)

def update_profile(request): # pragma: no cover
    if request.method == 'POST':
        kode_identitas = get_data_user(request, 'kode_identitas')
        pengguna = Teman.objects.get(npm = kode_identitas)
        fullname = request.POST['full_name']
        url_linkedin = request.POST['url_linkedin']
        print(url_linkedin)
        picture_url = request.POST['picture_url']
        email = request.POST['email']
        headline = request.POST['headline']
        pengguna.nama = fullname
        pengguna.url_linkedin = url_linkedin
        pengguna.foto = picture_url
        pengguna.email = email
        pengguna.headline = headline
        pengguna.save()
        response['Status_form'] = Status_Form
        kode_identitas = get_data_user(request,'kode_identitas')
        pengguna = Teman.objects.get(npm = kode_identitas)
        response['status'] = pengguna.status_set.all()
		# print(response['status'])
        stat = Status.objects.all().order_by('-id')
        if (len(stat) > 0):
            message = stat[0]
            newMessage = message.status
            time = message.created_date
        else:
            newMessage = "You have not posted yet"
            time = date(datetime.now().year,datetime.now().month,datetime.now().day)
        response['latestMessage'] = newMessage
        response['jumlah_status'] = pengguna.status_set.count()
        response['daftar_riwayat'] = views.get_daftar_riwayat()
        return HttpResponseRedirect(reverse('a2:edit_profile'))

def add_status(request): # pragma: no cover
	kode_identitas = get_data_user(request,'kode_identitas')
	pengguna = Teman.objects.get(npm = kode_identitas)
	form = Status_Form(request.POST or None)
	if(request.method == 'POST' and form.is_valid()):
		response['status'] = request.POST['status']
		status = Status(status=response['status'], pengguna=pengguna)
		status.save()
	return HttpResponseRedirect(reverse('a2:index'))

def delete_status(request, id): # pragma: no cover
	kode_identitas = get_data_user(request,'kode_identitas')
	pengguna = Teman.objects.get(npm = kode_identitas)
	status = pengguna.status_set.filter(pk=id)
	status.delete()
	return HttpResponseRedirect(reverse('a2:index'))

a2/templates/a2/tables/profile.html
<div class="panel panel-info">
    <div class="panel-heading">
    </div>
    <div class="panel-body">
        <p><b>Nama: </b>{{ user.name }}</p>
        <p><b>NPM: </b>{{ user.npm }}</p>
        <p><b>Keahlian: </b>{{ user.mastery }}</p>
        <p><b>Email: </b>{{ user.email }}</p>
        <p><b>Link profile: </b>{{ user.profileLinkedin }}</p>
        <p>
    </div>
</div>

a2/templates/a2/tables/riwayat.html
<div class="panel panel-info">
    <div class="panel-heading">
        <h2> Daftar Optical : {{ optical | length}} </h2>
            Reset Favorite Optical
        </a>
    </div>
    <div class="panel-body">
        <table class="table">
            <thead>
            <th> No</th>
            <th> Nama</th>
            <th> Harga</th>
            <th> Jumlah</th>
            <th> Aksi </th>

            </thead>
            <tbody>
            {% for optic in optical %}
            <tr>
                <td> {{ forloop.counter }}</td>
                <td> {{ optic.name }}</td>
                <td> {{ optic.price }}</td>
                <td> {{ optic.quantity }}</td>
                <td>
                    {% if not optic.id in fav_optical %}
                    {% else %}
                    {% endif %}
                </td>
            </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
</div>

a2/templates/a2/tables/status.html
<!-- show status -->
<section name="my-list" id="my-list" style="padding-bottom: 20px">
        <section name="input-status" id="input-status">
                <form id="form" method="POST" action="{% url 'a2:add' %}">
                    <h3><b>What's on your mind?</b></h3>
                    {% csrf_token %}
                    {{ status_form }}
                    <br>
                    <input id="submit" type="submit" class="btn btn-md btn-info" value="Post">
                </form>
        </section>
    {% if status %}
    <div class="container"> 
        {% for data in status %}
            <div class="kotak" style="padding-top: 15px">
                <div class="row">
                    <div class="col-sm-8">
                        <div class="media" style="padding: 40px">
                            <div class="media-left ">
                                <!-- <img src="https://assets.teenvogue.com/photos/59922529fc885e5cc9aba96e/master/pass/GettyImages-546939180.jpg" class="media-object img-circle" style="width:60px"> --><!--foto nanti diganti dgn foto di hal profile-->
                                <span class="glyphicon glyphicon-user pull-left"></span>
                            </div>
                            <div class="media-body">
                                <h4 class="media-heading"><strong>{{profile_name}}</strong> <small><i>Posted on {{data.created_date}}</i></small></h4><!--nama nanti diganti dgn nama di hal profile-->
                                <p>{{data.status}}</p>
                            </div>
                        </div>
                    </div>
                    <!-- Tombol delete -->
                    <div class="col-md-4">
                        <a href="{% url 'a2:delete' data.id %}" class="btn btn-danger">Delete</a>
                    </div>
                </div>
            </div>
        {% endfor %}
    {% else %}
        <div class="alert alert-danger text-center">
            <strong>Oops!</strong> Belum ada status.
        </div>
    {% endif %}
    </section>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<script type="text/javascript">
    $(document).ready(function () {
        alert("ASDASDA");
        var show_form = '{{ status_form }}';
        console.log(show_form);
        if (show_form == 'True') {
            console.log(show_form)
            $('#input-status').hide();
            $('.status-list-delete').hide();
        }
        else{
            console.log("TEST");
            $('#input-status').show();
            $('.status-list-delete').show();
        }
    });
</script>